/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.bprasojo.ekspedisi;

import com.bprasojo.ekspedisi.dao.BankDAO;
import com.bprasojo.ekspedisi.dao.KasBonKaryawanDAO;
import com.bprasojo.ekspedisi.dao.PembayaranKasBonDAO;
import com.bprasojo.ekspedisi.model.Bank;
import com.bprasojo.ekspedisi.model.KasBonKaryawan;
import com.bprasojo.ekspedisi.model.PembayaranKasBon;
import com.bprasojo.ekspedisi.model.User;
import com.bprasojo.ekspedisi.utils.AppUtils;
import com.bprasojo.ekspedisi.utils.CustomFocusTraversalPolicy;
import com.bprasojo.ekspedisi.utils.LookupForm;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 */
public class FrmPembayaranKasBon extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmKasBonKaryawan
     */
    
    User user; 
    PembayaranKasBon pembayaranKasBon = null;
    PembayaranKasBonDAO pembayaranKasBonDAO = null;
    
//    Bank bank = null;    
    BankDAO bankDAO = null;
    
    KasBonKaryawan kasBonKaryawan = null;
    KasBonKaryawanDAO kasBonKaryawanDAO = null;
    
    private int currentPage = 1;
    private boolean SilakanLoadData = false;
    
    private DefaultTableModel tableModel;
//    private boolean showLoopUpBank = false;
    
    public FrmPembayaranKasBon(User user) {
        this();
        this.user = user;
    }
    public FrmPembayaranKasBon() {
        initComponents();
        
        
        
        try {
            setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmPembayaranKasBon.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        bankDAO = new BankDAO();
        pembayaranKasBonDAO = new PembayaranKasBonDAO();
        kasBonKaryawanDAO = new KasBonKaryawanDAO();
        
        AppUtils.SetTanggalAwalBulan(edTglAwal);
        AppUtils.SetTanggalToday(edTglAkhir);
        edFilter.setText("");
        
        InisialisasiTablePembayaranKasBon();
        
        SilakanLoadData = true;
        LoadDataPembayaranKasBon(currentPage);
        setStatusTombol("awal");
        
        
        inisialisasiEventTableModel();
        LoadBank();
        
        pnlInput.setFocusTraversalPolicy(new CustomFocusTraversalPolicy(edKasBon, btnKasBon, edTanggal, cbBank, edNominal, edKeterangan));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnJurnal = new javax.swing.JButton();
        pnlInput = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        edNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edAlamat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        edTanggal = new com.toedter.calendar.JDateChooser();
        cbBank = new javax.swing.JComboBox<>();
        edNominal = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        edKeterangan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        eNoRegister = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        edKasBon = new javax.swing.JTextField();
        btnKasBon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        edSaldo = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        pnlFilter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edTglAwal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        edTglAkhir = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        edFilter = new javax.swing.JTextField();
        pnlNextPrev = new javax.swing.JPanel();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPembayaranKasBon = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pembayaran Kas Bon Karyawan");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add32.png"))); // NOI18N
        btnNew.setText("Tambah");
        btnNew.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setMaximumSize(new java.awt.Dimension(60, 70));
        btnNew.setMinimumSize(new java.awt.Dimension(60, 70));
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNew);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit32.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setMaximumSize(new java.awt.Dimension(60, 70));
        btnEdit.setMinimumSize(new java.awt.Dimension(60, 70));
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEdit);

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save32.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSimpan.setFocusable(false);
        btnSimpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSimpan.setMaximumSize(new java.awt.Dimension(60, 70));
        btnSimpan.setMinimumSize(new java.awt.Dimension(60, 70));
        btnSimpan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSimpan);

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Undo32.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBatal.setFocusable(false);
        btnBatal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBatal.setMaximumSize(new java.awt.Dimension(60, 70));
        btnBatal.setMinimumSize(new java.awt.Dimension(60, 70));
        btnBatal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBatal);

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete32.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnHapus.setFocusable(false);
        btnHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHapus.setMaximumSize(new java.awt.Dimension(60, 70));
        btnHapus.setMinimumSize(new java.awt.Dimension(60, 70));
        btnHapus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHapus);

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close32.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnKeluar.setFocusable(false);
        btnKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKeluar.setMaximumSize(new java.awt.Dimension(60, 70));
        btnKeluar.setMinimumSize(new java.awt.Dimension(60, 70));
        btnKeluar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKeluar);

        btnJurnal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/jurnal.png"))); // NOI18N
        btnJurnal.setText("Jurnal");
        btnJurnal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnJurnal.setFocusable(false);
        btnJurnal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnJurnal.setMaximumSize(new java.awt.Dimension(60, 70));
        btnJurnal.setMinimumSize(new java.awt.Dimension(60, 70));
        btnJurnal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnJurnal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJurnalActionPerformed(evt);
            }
        });
        jToolBar1.add(btnJurnal);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.NORTH);

        pnlInput.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlInput.setFocusCycleRoot(true);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("No Reguster");

        edNama.setEditable(false);
        edNama.setEnabled(false);
        edNama.setNextFocusableComponent(edAlamat);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Alamat");

        edAlamat.setEditable(false);
        edAlamat.setEnabled(false);
        edAlamat.setNextFocusableComponent(edTanggal);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tanggal");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Kas/Bank");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Nominal");

        cbBank.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbBankItemStateChanged(evt);
            }
        });
        cbBank.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbBankPropertyChange(evt);
            }
        });

        edNominal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        edNominal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Keterangan");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Nama");

        eNoRegister.setEditable(false);
        eNoRegister.setText("Otomatis");
        eNoRegister.setEnabled(false);
        eNoRegister.setNextFocusableComponent(edAlamat);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Kas Bon");

        edKasBon.setFocusCycleRoot(true);

        btnKasBon.setText("...");
        btnKasBon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKasBonActionPerformed(evt);
            }
        });

        jLabel3.setText("Saldo Hutang");

        edSaldo.setEditable(false);
        edSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        edSaldo.setEnabled(false);

        javax.swing.GroupLayout pnlInputLayout = new javax.swing.GroupLayout(pnlInput);
        pnlInput.setLayout(pnlInputLayout);
        pnlInputLayout.setHorizontalGroup(
            pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputLayout.createSequentialGroup()
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputLayout.createSequentialGroup()
                        .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlInputLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edNama, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlInputLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(eNoRegister)
                                .addGroup(pnlInputLayout.createSequentialGroup()
                                    .addComponent(edKasBon, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnKasBon, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                            .addComponent(edSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(edNominal, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edKeterangan)
                    .addComponent(edTanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(cbBank, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        pnlInputLayout.setVerticalGroup(
            pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(eNoRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(edTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12)
                    .addComponent(edKasBon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKasBon)
                    .addComponent(jLabel7)
                    .addComponent(cbBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(edSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(edNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(edKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(edAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnlInput, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Periode");

        edTglAwal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                edTglAwalPropertyChange(evt);
            }
        });

        jLabel2.setText("s.d.");

        edTglAkhir.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                edTglAkhirPropertyChange(evt);
            }
        });

        jLabel10.setText("Filter");

        edFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edFilterKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlFilterLayout = new javax.swing.GroupLayout(pnlFilter);
        pnlFilter.setLayout(pnlFilterLayout);
        pnlFilterLayout.setHorizontalGroup(
            pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilterLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edTglAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(edTglAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        pnlFilterLayout.setVerticalGroup(
            pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edTglAwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edTglAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(edFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanel3.add(pnlFilter, java.awt.BorderLayout.NORTH);

        pnlNextPrev.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnPrev.setText("<< Prev");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNextPrevLayout = new javax.swing.GroupLayout(pnlNextPrev);
        pnlNextPrev.setLayout(pnlNextPrevLayout);
        pnlNextPrevLayout.setHorizontalGroup(
            pnlNextPrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNextPrevLayout.createSequentialGroup()
                .addContainerGap(553, Short.MAX_VALUE)
                .addComponent(btnPrev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext)
                .addContainerGap())
        );
        pnlNextPrevLayout.setVerticalGroup(
            pnlNextPrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNextPrevLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlNextPrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnPrev))
                .addContainerGap())
        );

        jPanel3.add(pnlNextPrev, java.awt.BorderLayout.PAGE_END);

        tblPembayaranKasBon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPembayaranKasBon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblPembayaranKasBonFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(tblPembayaranKasBon);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        LoadDataPembayaranKasBon(currentPage);
        
        pembayaranKasBon = new PembayaranKasBon();
        kasBonKaryawan = null;
//        bank = null;
        
        AppUtils.setDefaultValues(edKasBon, edNama, edAlamat, edTanggal, edNominal, edKeterangan, cbBank);
        
//        showLoopUpBank = true;
        
        setStatusTombol("tambah");
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        setStatusTombol("edit");
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (validasiInput() == false){
            return;
        }

        try {
            pembayaranKasBon.setKasBonKaryawanId(kasBonKaryawan.getId());
            pembayaranKasBon.setSumberDana(cbBank.getSelectedItem().toString());
            pembayaranKasBon.setTanggal(edTanggal.getDate());
            
            Bank selectedBank = (Bank) cbBank.getSelectedItem();
            pembayaranKasBon.setBankId(selectedBank.getId());
            pembayaranKasBon.setPerkiraanKasId(selectedBank.getAkun().getId());            
            
            pembayaranKasBon.setNominal(((Number)edNominal.getValue()).intValue());
            pembayaranKasBon.setKeterangan(edKeterangan.getText());
            pembayaranKasBon.setUserCreate(user.getUsername());
            pembayaranKasBon.setUserUpdate(user.getUsername());
            
            pembayaranKasBonDAO.save(pembayaranKasBon);

            AppUtils.showInfoDialog("Data berhasil disimpan dengan no register : " + pembayaranKasBon.getNoRegister());
            LoadDataPembayaranKasBon(currentPage);

        } catch (SQLException ex) {
            AppUtils.showErrorDialog("Gagal menyimpan data dengan error " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        setStatusTombol("awal");
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        boolean userConfirmed = AppUtils.showConfirmDialog("Apakah Anda yakin akan menghapus data?");

        if (userConfirmed) {
            try {
                pembayaranKasBonDAO.delete(pembayaranKasBon.getId());
                setStatusTombol("awal");
                LoadDataPembayaranKasBon(currentPage);
            } catch (SQLException ex) {
                AppUtils.showErrorDialog("Gagal menghapus data dengan error: \n" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void edTglAwalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_edTglAwalPropertyChange
        if (SilakanLoadData){
            currentPage = 1;
            LoadDataPembayaranKasBon(currentPage);
        }
    }//GEN-LAST:event_edTglAwalPropertyChange

    private void edTglAkhirPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_edTglAkhirPropertyChange
        if (SilakanLoadData){
            currentPage = 1;
            LoadDataPembayaranKasBon(currentPage);
        }
    }//GEN-LAST:event_edTglAkhirPropertyChange

    private void edFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edFilterKeyReleased
        if (SilakanLoadData){
            currentPage = 1;
            LoadDataPembayaranKasBon(currentPage);
        }
    }//GEN-LAST:event_edFilterKeyReleased

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        if (currentPage > 1) {
            currentPage--;
            LoadDataPembayaranKasBon(currentPage);
        }
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        currentPage++;
        LoadDataPembayaranKasBon(currentPage);
    }//GEN-LAST:event_btnNextActionPerformed

    private void tblPembayaranKasBonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblPembayaranKasBonFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPembayaranKasBonFocusGained

    private void cbBankPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbBankPropertyChange
        
    }//GEN-LAST:event_cbBankPropertyChange

    private void cbBankItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbBankItemStateChanged
//        if (evt.getStateChange() == ItemEvent.SELECTED && showLoopUpBank){
//            if (cbBank.getSelectedIndex() <= 0){
//                bank = null;
//                lblBank.setText("");
//            } else {
//                String sqlQuery = "select no_rekening, nama_bank, atas_nama from bank";
//                LookupForm lookupForm = new LookupForm(this, sqlQuery, true);
//                Map<String, Object> selectedRecord = lookupForm.getSelectedRecord();
//                if (selectedRecord != null) {
//                    try {
//                        // Mengambil nilai dengan nama kolom
//                        String no_rekening = selectedRecord.get("no_rekening").toString();
//                        bank = bankDAO.getBankByNoRekening(no_rekening);
//
//                        if (bank != null){
//                            lblBank.setText(bank.toString());
//                        } else {
//                            lblBank.setText("");
//                        }
//                    } catch (SQLException ex) {
//                        Logger.getLogger(FrmTransaksiBank.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//
//                } else {
//                    JOptionPane.showMessageDialog(this, "Tidak ada data yang dipilih.");
//                }
//            }
//        }
    }//GEN-LAST:event_cbBankItemStateChanged

    private void btnKasBonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKasBonActionPerformed
        String sqlQuery = "select no_register, b.kode, b.nama , b.alamat , b.no_ktp, nominal, pelunasan, "
                          + " (nominal - pelunasan) as saldo, status_lunas "
                          + " from kas_bon_karyawan a "
                          + " inner join stake_holder b on a.karyawan_id = b.id"
                          + " where status_lunas = 'belum'";
        
        LookupForm lookupForm = new LookupForm(this, sqlQuery, true);
        Map<String, Object> selectedRecord = lookupForm.getSelectedRecord();
        if (selectedRecord != null) {
            try {
                // Mengambil nilai dengan nama kolom
                String no_register = selectedRecord.get("no_register").toString();
                kasBonKaryawan = kasBonKaryawanDAO.getByNoRegister(no_register);

                if (kasBonKaryawan != null){
                    edKasBon.setText(kasBonKaryawan.getNoRegister());
                    edNama.setText(kasBonKaryawan.getKaryawan().getNama());
                    edAlamat.setText(kasBonKaryawan.getKaryawan().getAlamat());
                    edSaldo.setValue(kasBonKaryawan.getSaldo());

                }
            } catch (SQLException ex) {
                AppUtils.showWarningDialog("Ada kesalahan load data kasbon dengan error \n" + ex.getMessage());
            }

        }
    }//GEN-LAST:event_btnKasBonActionPerformed

    private void btnJurnalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJurnalActionPerformed
        if (pembayaranKasBon == null) {
            AppUtils.showErrorDialog("Tidak ada transaksi yang akan dijurnal");
            return;
        }

        try {
            // Cek apakah transaksi sudah dijurnal
            if (pembayaranKasBonDAO.isSudahJurnal(pembayaranKasBon.getNoRegister())) {
                boolean userConfirmed = AppUtils.showConfirmDialog(
                    "Transaksi ini sudah dijurnal. \nApakah anda yakin akan menjurnal ulang?");

                if (!userConfirmed) return;
            }

            // Proses jurnal
            Connection conn = pembayaranKasBonDAO.getConnection();
            boolean previousAutoCommit = conn.getAutoCommit();
            conn.setAutoCommit(false);

            try {
                pembayaranKasBonDAO.saveJurnal(pembayaranKasBon);
                conn.commit();
                setStatusTombol("selected");
                AppUtils.showInfoDialog("Berhasil simpan jurnal");
            } catch (SQLException ex) {
                conn.rollback();
                AppUtils.showErrorDialogSimpan(ex);
            } finally {
                conn.setAutoCommit(previousAutoCommit);
            }
        } catch (SQLException ex) {
            AppUtils.showErrorDialogSimpan(ex);
        }
    }//GEN-LAST:event_btnJurnalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnJurnal;
    private javax.swing.JButton btnKasBon;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<Bank> cbBank;
    private javax.swing.JTextField eNoRegister;
    private javax.swing.JTextField edAlamat;
    private javax.swing.JTextField edFilter;
    private javax.swing.JTextField edKasBon;
    private javax.swing.JTextField edKeterangan;
    private javax.swing.JTextField edNama;
    private javax.swing.JFormattedTextField edNominal;
    private javax.swing.JFormattedTextField edSaldo;
    private com.toedter.calendar.JDateChooser edTanggal;
    private com.toedter.calendar.JDateChooser edTglAkhir;
    private com.toedter.calendar.JDateChooser edTglAwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnlFilter;
    private javax.swing.JPanel pnlInput;
    private javax.swing.JPanel pnlNextPrev;
    private javax.swing.JTable tblPembayaranKasBon;
    // End of variables declaration//GEN-END:variables

    private void setStatusTombol(String mode){
        btnJurnal.setEnabled(false);
        
        if (null != mode)switch (mode) {
            case "awal" -> {
                btnNew.setEnabled(true);
                btnEdit.setEnabled(false);
                btnSimpan.setEnabled(false);
                btnBatal.setEnabled(false);
                btnHapus.setEnabled(false);
                SetEnableKomponenInput(false);
            }
            case "tambah" -> {
                btnNew.setEnabled(false);
                btnEdit.setEnabled(false);
                btnSimpan.setEnabled(true);
                btnBatal.setEnabled(true);
                btnHapus.setEnabled(false);
                SetEnableKomponenInput(true);
            }
            case "edit" -> {
                btnNew.setEnabled(false);
                btnEdit.setEnabled(false);
                btnSimpan.setEnabled(true);
                btnBatal.setEnabled(true);
                btnHapus.setEnabled(true);
                btnJurnal.setEnabled(true);
                SetEnableKomponenInput(true);
            }
            case "selected" -> {
                btnNew.setEnabled(true);
                btnEdit.setEnabled(true);
                btnSimpan.setEnabled(false);
                btnBatal.setEnabled(false);
                btnHapus.setEnabled(true);
                SetEnableKomponenInput(false);
            }
            default -> {
            }
        }
    }

    private boolean validasiInput() {
        if (kasBonKaryawan == null){
            AppUtils.showWarningDialog("Kas bon belum dipilih");
            btnKasBon.requestFocus();
            return false;
        }
        
        if (cbBank.getSelectedIndex() < 0){
            AppUtils.showWarningDialog("Via bank belum dipilih");
            cbBank.requestFocus();
            return false;
        }
        
        if (cbBank.getSelectedIndex() < 0){
            AppUtils.showWarningDialog("Bank belum dipilih");
            cbBank.requestFocus();
            return false;
        }
        
        if (edNominal.getValue() == null || ((Number) edNominal.getValue()).intValue() <= 0){
            AppUtils.showWarningDialog("Nominal belum diisi");
            edNominal.requestFocus();
            return false;
        }
        
        int saldo = ((Number) edSaldo.getValue()).intValue();
        int pembayaran = ((Number) edNominal.getValue()).intValue();
        if (saldo < pembayaran){
            AppUtils.showWarningDialog("Pembayaran melebihi saldo hutang");
            edNominal.requestFocus();
            return false;
        }
        
        
        return true;
        
    }
    
    private void inisialisasiEventTableModel() {
        tblPembayaranKasBon.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // Memeriksa apakah ada baris yang dipilih
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = tblPembayaranKasBon.getSelectedRow(); // Mendapatkan baris yang dipilih
                    if (selectedRow != -1) {
                        Integer id = (Integer) tblPembayaranKasBon.getModel().getValueAt(selectedRow, 0);
                        LoadPembayaranKasBon(id);
                        setStatusTombol("selected");
                    }
                }
            }

            private void LoadPembayaranKasBon(Integer id) {
                try {
                    pembayaranKasBon = pembayaranKasBonDAO.getById(id);
                    if (pembayaranKasBon != null){
                        kasBonKaryawan = kasBonKaryawanDAO.getById(pembayaranKasBon.getKasBonKaryawanId());
                        eNoRegister.setText(pembayaranKasBon.getNoRegister());
                        
                        edKasBon.setText(kasBonKaryawan.getNoRegister());
                        
                        edNama.setText(kasBonKaryawan.getKaryawan().getNama());
                        edAlamat.setText(kasBonKaryawan.getKaryawan().getAlamat());
                        
                        Integer saldo = kasBonKaryawan.getSaldo() + pembayaranKasBon.getNominal();
                        edSaldo.setValue(saldo);
                        
                        edTanggal.setDate(pembayaranKasBon.getTanggal());
                        
                        if (pembayaranKasBon.getBankId() > 0){
                            AppUtils.setSelectedIndexById(cbBank, pembayaranKasBon.getBankId());
                        } else {
                          cbBank.setSelectedIndex(-1);
                        }
                        
                        edNominal.setValue(pembayaranKasBon.getNominal());
                        edKeterangan.setText(pembayaranKasBon.getKeterangan());
                        
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(FrmPembayaranKasBon.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    private void LoadDataPembayaranKasBon(int currentPage) {
        tableModel.setRowCount(0); // Bersihkan tabel
        
        List<Map<String, Object>> result = pembayaranKasBonDAO.getPembayaranKasBonByPage(currentPage, edTglAwal.getDate(), edTglAkhir.getDate(), edFilter.getText());
        for (Map<String, Object> row : result) {
//            {"ID","Jenis Kas Bon", "Nama", "Alamat", "Tanggal", "Suber Dana","Nominal", "Pelunasan","Status", "Keterangan",  "Pc"}
            
            Integer hutang = (Integer) row.get("hutang");
            Integer pembayaran = (Integer) row.get("nominal");
            Integer saldo = hutang - pembayaran;
            tableModel.addRow(new Object[]{
                        (Integer) row.get("id"),
                        (String) row.get("no_register"),
                        (String) row.get("no_kas_bon"),    
                        (String) row.get("nama_karyawan"),
                        (String) row.get("alamat_karyawan"),
                        AppUtils.DateFormatShort((Date) row.get("tanggal")),
                        (String) row.get("sumber_dana"),
                        AppUtils.NumericFormat(hutang),
                        AppUtils.NumericFormat(pembayaran),
                        AppUtils.NumericFormat(saldo),
                        (String) row.get("keterangan"),
                        (String) row.get("user_create")
                });
        }
        
        tblPembayaranKasBon.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        
    }

    private void SetEnableKomponenInput(boolean enable) {
        edKasBon.setEnabled(enable);
        btnKasBon.setEnabled(enable);
        
//        edNama.setEnabled(enable);
//        edAlamat.setEnabled(enable);
        edTanggal.setEnabled(enable);
        cbBank.setEnabled(enable);
        edNominal.setEnabled(enable);
        edKeterangan.setEnabled(enable);
    }

    private void InisialisasiTablePembayaranKasBon() {
        tableModel = new DefaultTableModel(new String[]{"ID","No Register", "No Kas Bon", "Nama", "Alamat", "Tanggal", "Suber Dana","Hutang","Pembayaran","Saldo Hutang", "Keterangan",  "Pc"}, 0);
        tblPembayaranKasBon.setModel(tableModel);
        AppUtils.SetTableAligmentRight(tblPembayaranKasBon, 7);
        tblPembayaranKasBon.removeColumn(tblPembayaranKasBon.getColumnModel().getColumn(0));
        
    }
    
     private void LoadBank() {
        try {
            List<Bank> banks = bankDAO.getAllBank();
            
            // Masukkan data ke JComboBox
            DefaultComboBoxModel<Bank> model = new DefaultComboBoxModel<>();
            for (Bank b : banks) {
                model.addElement(b); // Menambahkan objek Perkiraan ke model
            }
            cbBank.setModel(model);
        } catch (SQLException ex) {
            AppUtils.showWarningDialog("Gagal load bank dengan error : \n" + ex.getMessage());
        }
    }
}
