/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.bprasojo.ekspedisi;

import com.bprasojo.ekspedisi.dao.PerkiraanDAO;
import com.bprasojo.ekspedisi.model.Perkiraan;
import com.bprasojo.ekspedisi.model.User;
import com.bprasojo.ekspedisi.utils.AppUtils;
import com.bprasojo.ekspedisi.utils.LookupForm;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author USER
 */
public class FrmPerkiraan extends FrmDefault {

    /**
     * Creates new form FrmPerkiraan
     */
    private User user;
    private Perkiraan perkiraan;
    private PerkiraanDAO perkiraanDAO;
    private Perkiraan perkiraan_parent;
    
    public FrmPerkiraan(User user) {
        this();
        this.user = user;
    }
    
    public FrmPerkiraan() {
        super();
        initComponents();
        btnJurnal.setVisible(false);
        
        setStatusTombol("awal");        
        
        perkiraanDAO = new PerkiraanDAO();
        try {
            loadPerkiraanTree();
        } catch (SQLException ex) {
            AppUtils.showErrorDialog(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnJurnal = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreePerkiraan = new javax.swing.JTree();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edNamaAkunParent = new javax.swing.JTextField();
        btnAkunParent = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        edKode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edNama = new javax.swing.JTextField();
        cbKelompok = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbGolongan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbSaldoNormal = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Perkiraan");

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add32.png"))); // NOI18N
        btnNew.setText("Tambah");
        btnNew.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setMaximumSize(new java.awt.Dimension(60, 70));
        btnNew.setMinimumSize(new java.awt.Dimension(60, 70));
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNew);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit32.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setMaximumSize(new java.awt.Dimension(60, 70));
        btnEdit.setMinimumSize(new java.awt.Dimension(60, 70));
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEdit);

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save32.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSimpan.setFocusable(false);
        btnSimpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSimpan.setMaximumSize(new java.awt.Dimension(60, 70));
        btnSimpan.setMinimumSize(new java.awt.Dimension(60, 70));
        btnSimpan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSimpan);

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Undo32.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBatal.setFocusable(false);
        btnBatal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBatal.setMaximumSize(new java.awt.Dimension(60, 70));
        btnBatal.setMinimumSize(new java.awt.Dimension(60, 70));
        btnBatal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBatal);

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete32.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnHapus.setFocusable(false);
        btnHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHapus.setMaximumSize(new java.awt.Dimension(60, 70));
        btnHapus.setMinimumSize(new java.awt.Dimension(60, 70));
        btnHapus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHapus);

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close32.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnKeluar.setFocusable(false);
        btnKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKeluar.setMaximumSize(new java.awt.Dimension(60, 70));
        btnKeluar.setMinimumSize(new java.awt.Dimension(60, 70));
        btnKeluar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKeluar);

        btnJurnal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/jurnal.png"))); // NOI18N
        btnJurnal.setText("Jurnal");
        btnJurnal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnJurnal.setFocusable(false);
        btnJurnal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnJurnal.setMaximumSize(new java.awt.Dimension(60, 70));
        btnJurnal.setMinimumSize(new java.awt.Dimension(60, 70));
        btnJurnal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnJurnal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJurnalActionPerformed(evt);
            }
        });
        jToolBar1.add(btnJurnal);

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.32.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRefresh.setFocusable(false);
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefresh.setMaximumSize(new java.awt.Dimension(60, 70));
        btnRefresh.setMinimumSize(new java.awt.Dimension(60, 70));
        btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRefresh);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jTreePerkiraan.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreePerkiraanValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTreePerkiraan);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Parent");

        edNamaAkunParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNamaAkunParentActionPerformed(evt);
            }
        });

        btnAkunParent.setText("...");
        btnAkunParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAkunParentActionPerformed(evt);
            }
        });

        jLabel2.setText("Kode");

        jLabel3.setText("Nama");

        cbKelompok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AKTIVA", "PASIVA", "KEWAJIBAN", "EQUITAS", "PENDAPATAN", "BIAYA" }));

        jLabel4.setText("Kelompok");

        jLabel5.setText("Golongan");

        cbGolongan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AKTIVA", "PASIVA", "LABA/RUGI" }));

        jLabel6.setText("Saldo Normal");

        cbSaldoNormal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEBET", "KREDIT" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edNamaAkunParent)
                    .addComponent(edKode)
                    .addComponent(edNama)
                    .addComponent(cbKelompok, 0, 274, Short.MAX_VALUE)
                    .addComponent(cbGolongan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbSaldoNormal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAkunParent)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edNamaAkunParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAkunParent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKelompok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cbSaldoNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(273, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        setStatusTombol("tambah");
        perkiraan = new Perkiraan();
        perkiraan_parent = null;
        edKode.setText("");
        edNama.setText("");
        edNamaAkunParent.setText("");
        
    }//GEN-LAST:event_btnNewActionPerformed

    private void setStatusTombol(String mode){
        btnJurnal.setEnabled(false);
        
        if (null != mode)switch (mode) {
            case "awal" -> {
                btnNew.setEnabled(true);
                btnEdit.setEnabled(false);
                btnSimpan.setEnabled(false);
                btnBatal.setEnabled(false);
                btnHapus.setEnabled(false);
                SetEnableKomponenInput(false);
            }
            case "tambah" -> {
                btnNew.setEnabled(false);
                btnEdit.setEnabled(false);
                btnSimpan.setEnabled(true);
                btnBatal.setEnabled(true);
                btnHapus.setEnabled(false);
                SetEnableKomponenInput(true);
            }
            case "edit" -> {
                btnNew.setEnabled(false);
                btnEdit.setEnabled(false);
                btnSimpan.setEnabled(true);
                btnBatal.setEnabled(true);
                btnHapus.setEnabled(true);
                
                btnJurnal.setEnabled(true);
                SetEnableKomponenInput(true);
            }
            case "selected" -> {
                btnNew.setEnabled(true);
                btnEdit.setEnabled(true);
                btnSimpan.setEnabled(false);
                btnBatal.setEnabled(false);
                btnHapus.setEnabled(true);
                SetEnableKomponenInput(false);
            }
            default -> {
            }
        }
    }
    
    private void SetEnableKomponenInput(boolean enable) {
        edNamaAkunParent.setEnabled(enable);
        btnAkunParent.setEnabled(enable);
        edKode.setEnabled(enable);
        edNama.setEnabled(enable);
        cbKelompok.setEnabled(enable);
        cbGolongan.setEnabled(enable);
        cbSaldoNormal.setEnabled(enable);
//        edLevel.setEnabled(enable);
    }
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        setStatusTombol("edit");
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (validasiInput() == false){
            return;
        }
        
        perkiraan.setKode(edKode.getText());
        perkiraan.setNama(edNama.getText());
        perkiraan.setGolongan(cbGolongan.getSelectedItem().toString());
        perkiraan.setKelompok(cbKelompok.getSelectedItem().toString());
        
        if (perkiraan_parent == null){
            perkiraan.setLevel(0);
        } else {
            perkiraan.setLevel(perkiraan_parent.getLevel() + 1);
        }
        
        perkiraan.setParent_Id(perkiraan_parent.getId());
        perkiraan.setSaldo_normal(Perkiraan.SaldoNormal.valueOf(cbSaldoNormal.getSelectedItem().toString()));
        
        try {
            perkiraanDAO.save(perkiraan);
            AppUtils.showInfoDialog("Berhasil simpan perkiraan");
        } catch (SQLException ex) {
            AppUtils.showErrorDialogSimpan(ex);
        }        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        setStatusTombol("awal");
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if (perkiraan == null){
            AppUtils.showWarningDialog("Tidak ada data yang akan dihapus");
            return;
        }
        
        try {
            if (perkiraanDAO.isPunyaAnak(perkiraan.getKode())){
                AppUtils.showWarningDialog("Data tidak bisa dihapus karena mempunyai perkiraan anak");
                return;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(FrmPerkiraan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        boolean userConfirmed = AppUtils.showConfirmDialog("Apakah Anda yakin akan menghapus data?");
        
        if (userConfirmed == false){
            return;
        }
        
        try {
            perkiraanDAO.deletePerkiraan(perkiraan.getId());
            AppUtils.showInfoDialog("Berhasil hapus data");
            btnRefreshActionPerformed(evt);
        } catch (SQLException ex) {
            AppUtils.showErrorDialogHapus(ex);
        }
        
        

        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnJurnalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJurnalActionPerformed
        
    }//GEN-LAST:event_btnJurnalActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        try {
            loadPerkiraanTree();
            setStatusTombol("awal");
        } catch (SQLException ex) {
            AppUtils.showErrorDialog(ex.getMessage());
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void edNamaAkunParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNamaAkunParentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edNamaAkunParentActionPerformed

    private void btnAkunParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAkunParentActionPerformed
        String sqlQuery = "SELECT " +
        " concat(REPEAT(' ', level * 4), kode) as kode_akun, " +
        " concat(REPEAT(' ', level * 4), nama) as nama_akun, id " +
        " FROM perkiraan " +
        " ORDER BY kode";

        LookupForm lookupForm = new LookupForm(this, sqlQuery, true);
        Map<String, Object> selectedRecord = lookupForm.getSelectedRecord();
        if (selectedRecord != null) {
            try {
                // Mengambil nilai dengan nama kolom
                String kode = selectedRecord.get("kode_akun").toString().trim();
                perkiraan_parent = perkiraanDAO.getPerkiraanByKode(kode);
                
                edNamaAkunParent.setText(perkiraan_parent.toString());
            } catch (SQLException ex) {
                Logger.getLogger(FrmTransaksiKas.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnAkunParentActionPerformed

    private void jTreePerkiraanValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreePerkiraanValueChanged
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTreePerkiraan.getLastSelectedPathComponent();
        
        if (selectedNode == null) return; // Tidak ada yang dipilih

        Object userObject = selectedNode.getUserObject();

        // Jika node menyimpan data Perkiraan, tampilkan detailnya
        if (userObject instanceof Perkiraan) {
            try {
                int id_perkiraan = ((Perkiraan) userObject).getId();
                perkiraan = perkiraanDAO.getById(id_perkiraan);
                
                tampilkanDetailPerkiraan(perkiraan);
                setStatusTombol("selected");
            } catch (SQLException ex) {
                AppUtils.showConfirmDialog("Gagal Load Perkiraan\n" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jTreePerkiraanValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAkunParent;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnJurnal;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbGolongan;
    private javax.swing.JComboBox<String> cbKelompok;
    private javax.swing.JComboBox<String> cbSaldoNormal;
    private javax.swing.JTextField edKode;
    private javax.swing.JTextField edNama;
    private javax.swing.JTextField edNamaAkunParent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jTreePerkiraan;
    // End of variables declaration//GEN-END:variables

    private boolean validasiInput() {
        
        if (perkiraan_parent == null){
            if (AppUtils.showConfirmDialog("Anda yakin menyimpan perkiraan level 1") == false){
                return false;
            }
        }
        
        if (edKode.getText().equals("")){
            AppUtils.showWarningDialog("Kode belum diisi");
            edKode.requestFocus();
            return false;
        }
        
        if (edNama.getText().equals("")){
            AppUtils.showWarningDialog("Nama belum diisi");
            edNama.requestFocus();
            return false;
        }
        
        if (cbKelompok.getSelectedIndex() < 0){
            AppUtils.showWarningDialog("Kelompok belum dipilih");
            cbKelompok.requestFocus();
            return false;
        }
        
        if (cbGolongan.getSelectedIndex() < 0){
            AppUtils.showWarningDialog("Golongan belum dipilih");
            cbGolongan.requestFocus();
            return false;
        }
        
        if (cbSaldoNormal.getSelectedIndex() < 0){
            AppUtils.showWarningDialog("Saldo Normal belum dipilih");
            cbSaldoNormal.requestFocus();
            return false;
        }
        
        if (AppUtils.showConfirmDialog("Anda yakin menyimpan data") == false){
            return false;
        }
        
        return true;
    }

    public void loadPerkiraanTree() throws SQLException {
        List<Perkiraan> semua = perkiraanDAO.getAllPerkiraan();

        Map<Integer, List<Perkiraan>> treeMap = new HashMap<>();
        for (Perkiraan p : semua) {
            treeMap.computeIfAbsent(p.getParent_Id(), k -> new ArrayList<>()).add(p);
        }

        // Root Node manual
        DefaultMutableTreeNode rootNode = new DefaultMutableTreeNode("Daftar Perkiraan");

        // Tambahkan semua Perkiraan dengan parent_id = 0
        List<Perkiraan> roots = treeMap.get(0);
        if (roots != null) {
            for (Perkiraan p : roots) {
                DefaultMutableTreeNode node = buildTreeNode(p, treeMap);
                rootNode.add(node);
            }
        }

        jTreePerkiraan.setModel(new DefaultTreeModel(rootNode));
    }

    private DefaultMutableTreeNode buildTreeNode(Perkiraan perkiraan, Map<Integer, List<Perkiraan>> treeMap) {
        DefaultMutableTreeNode node = new DefaultMutableTreeNode(perkiraan);
        List<Perkiraan> anak = treeMap.get(perkiraan.getId());
        if (anak != null) {
            for (Perkiraan p : anak) {
                node.add(buildTreeNode(p, treeMap));
            }
        }
        return node;
    }

    private void tampilkanDetailPerkiraan(Perkiraan perkiraan) throws SQLException {
        if (perkiraan != null){
            if (perkiraan.getParent_Id() > 0){
                perkiraan_parent = perkiraanDAO.getById(perkiraan.getParent_Id());
                edNamaAkunParent.setText(perkiraan_parent.toString());                
            } else {
                perkiraan_parent = null;
                edNamaAkunParent.setText("");                
            }
            
            edKode.setText(perkiraan.getKode());
            edNama.setText(perkiraan.getNama());
            cbGolongan.setSelectedItem(perkiraan.getGolongan());
            cbKelompok.setSelectedItem(perkiraan.getKelompok());
            cbSaldoNormal.setSelectedItem(perkiraan.getSaldo_normal().toString());
            
        } else {
            perkiraan_parent = null;
            
            edNamaAkunParent.setText("");
            edKode.setText("");
            edNama.setText("");
        }
    }

}
