package com.bprasojo.ekspedisi;

import com.bprasojo.ekspedisi.model.User;
import com.bprasojo.ekspedisi.utils.AppUtils;
import com.bprasojo.ekspedisi.utils.VersionUtils;
import java.beans.PropertyVetoException;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    
    User user = null;
    public MainForm() {
        initComponents();        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        setMenuItemsEnabled(false);
        
        String mode = System.getProperty("mode", "production"); // Default 'production'
        if ("production".equals(mode)) {
            String versi = VersionUtils.getAppVersion();
            setTitle("Ekspedisi Versi " + versi);
        } else {
            setTitle("Ekspedisi Developement Mode");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnLogin = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miCustomer = new javax.swing.JMenuItem();
        miArmada = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        miTransaksiKas = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenuBar1.setName("mainMenu"); // NOI18N

        jMenu1.setText("File");

        mnLogin.setText("Login");
        mnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLoginActionPerformed(evt);
            }
        });
        jMenu1.add(mnLogin);

        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master Data");

        miCustomer.setText("Customer");
        miCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCustomerActionPerformed(evt);
            }
        });
        jMenu2.add(miCustomer);

        miArmada.setText("Armada");
        miArmada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miArmadaActionPerformed(evt);
            }
        });
        jMenu2.add(miArmada);

        jMenuItem14.setText("Karyawan");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Keuangan");

        jMenu5.setText("Mutasi Kas");

        miTransaksiKas.setText("Transaksi Kas");
        miTransaksiKas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTransaksiKasActionPerformed(evt);
            }
        });
        jMenu5.add(miTransaksiKas);

        jMenuItem1.setText("Pembelian BBM");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);
        jMenu5.add(jSeparator1);

        jMenuItem4.setText("Rekap Transaksi Kas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem5.setText("Riwayat Pembelian BBM");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenu3.add(jMenu5);

        jMenu6.setText("Transaksi Bank");

        jMenuItem8.setText("Transaksi Bank");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuItem6.setText("Rekening Koran");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);
        jMenu6.add(jSeparator3);

        jMenuItem7.setText("Rekap Transaksi");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuItem9.setText("Rekap Saldo Bank");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenu3.add(jMenu6);

        jMenu7.setText("Kas Bon Karyawan");

        jMenuItem10.setText("Input Kas Bon");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem10);

        jMenuItem11.setText("Pembayaran Kas Bon");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem11);
        jMenu7.add(jSeparator2);

        jMenuItem12.setText("Rekap Transaksi");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem12);

        jMenuItem13.setText("Rekap Saldo Kasbon");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem13);

        jMenu3.add(jMenu7);

        jMenu8.setText("Invoice Customer");

        jMenuItem15.setText("Buat Invoice");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem15);

        jMenuItem16.setText("Pembayaran Invoice");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem16);
        jMenu8.add(jSeparator4);

        jMenuItem17.setText("Rekap Invoice Customer");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem17);

        jMenuItem18.setText("Rekap Pembayaran Invoice Customer");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem18);

        jMenu3.add(jMenu8);

        jMenu9.setText("Closing");

        jMenuItem19.setText("Closing");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem19);

        jMenu3.add(jMenu9);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Akuntansi");

        jMenuItem21.setText("Perkiraan / Akun");
        jMenu4.add(jMenuItem21);

        jMenuItem2.setText("Daftar Jurnal");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);
        jMenu4.add(jSeparator5);

        jMenuItem22.setText("Jenis Transaksi");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem22);

        jMenuBar1.add(jMenu4);

        jMenu10.setText("Setting");

        jMenuItem20.setText("Back Up Database");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem20);

        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miArmadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miArmadaActionPerformed
        FrmArmada frmArmada = new FrmArmada(user); // Buat instance FrmArmada
        desktopPane.add(frmArmada); // Tambahkan ke JDesktopPane
        frmArmada.setVisible(true); // Tampilkan FrmArmada
    }//GEN-LAST:event_miArmadaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void miTransaksiKasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTransaksiKasActionPerformed
        FrmTransaksiKas frmTransaksiKas = new FrmTransaksiKas(user);
        desktopPane.add(frmTransaksiKas);
        frmTransaksiKas.setVisible(true);
    }//GEN-LAST:event_miTransaksiKasActionPerformed

    private void miCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCustomerActionPerformed
        FrmCustomer frmCustomer = new FrmCustomer(user);
        frmCustomer.setTitle("Customer");
        frmCustomer.setJenis("Customer");
        frmCustomer.loadDataStakeHolder(1);
        frmCustomer.KonfigurasiForm();
        desktopPane.add(frmCustomer);        
        frmCustomer.setVisible(true);
    }//GEN-LAST:event_miCustomerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmInputBBM frmInputBBM = new FrmInputBBM(user);
        desktopPane.add(frmInputBBM);
        frmInputBBM.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FrmRptRekapTransaksiKas frmRptRekapTransaksiKas = new FrmRptRekapTransaksiKas();
        desktopPane.add(frmRptRekapTransaksiKas);
        frmRptRekapTransaksiKas.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        FrmRptRiwayatPembelianBBM frmRptRiwayatPembelianBBM = new FrmRptRiwayatPembelianBBM();
        desktopPane.add(frmRptRiwayatPembelianBBM);
        frmRptRiwayatPembelianBBM.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        FrmTransaksiBank frmTransaksiBank = new FrmTransaksiBank(user);
        desktopPane.add(frmTransaksiBank);
        frmTransaksiBank.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        FrmRptRekapTransaksiBank frmRptRekapTransaksiBank = new FrmRptRekapTransaksiBank();
        desktopPane.add(frmRptRekapTransaksiBank);
        frmRptRekapTransaksiBank.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        FrmRekeningKoranBank frmRekeningKoranBank = new FrmRekeningKoranBank();
        desktopPane.add(frmRekeningKoranBank);
        frmRekeningKoranBank.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        FrmSaldoBank frmSaldoBank = new FrmSaldoBank();
        desktopPane.add(frmSaldoBank);
        frmSaldoBank.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        FrmKasBonKaryawan frmKasBonKaryawan = new FrmKasBonKaryawan(user);
        desktopPane.add(frmKasBonKaryawan);
        frmKasBonKaryawan.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        FrmSaldoKasbon frmSaldoKasbon = new FrmSaldoKasbon();
        desktopPane.add(frmSaldoKasbon);
        frmSaldoKasbon.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        FrmPembayaranKasBon frmPembayaranKasBon = new FrmPembayaranKasBon(user);
        desktopPane.add(frmPembayaranKasBon);
        frmPembayaranKasBon.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        FrmRekapKasBon frmRekapKasBon = new FrmRekapKasBon();
        desktopPane.add(frmRekapKasBon);
        frmRekapKasBon.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        FrmCustomer frmCustomer = new FrmCustomer(user);
        frmCustomer.setTitle("Karyawan");
        frmCustomer.setJenis("Karyawan");
        frmCustomer.KonfigurasiForm();
        frmCustomer.loadDataStakeHolder(1);
        desktopPane.add(frmCustomer);        
        frmCustomer.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        FrmPembayaranTagihanCustomer frmPembayaranTagihanCustomer = new FrmPembayaranTagihanCustomer(user);
        desktopPane.add(frmPembayaranTagihanCustomer);
        frmPembayaranTagihanCustomer.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        FrmInvoice frmInvoice = new FrmInvoice(user);
        desktopPane.add(frmInvoice);
        frmInvoice.setVisible(true);
                
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        FrmRptRekapInvoiceCustomer frmRptRekapInvoiceCustomer = new FrmRptRekapInvoiceCustomer();
        desktopPane.add(frmRptRekapInvoiceCustomer);
        frmRptRekapInvoiceCustomer.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        FrmRptRekapPembayaranInvoiceCustomer frmRptRekapPembayaranInvoiceCustomer = new FrmRptRekapPembayaranInvoiceCustomer();
        desktopPane.add(frmRptRekapPembayaranInvoiceCustomer);
        frmRptRekapPembayaranInvoiceCustomer.setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        FrmClosing frmClosing = new FrmClosing();
        desktopPane.add(frmClosing);
        frmClosing.setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void mnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLoginActionPerformed
        if (mnLogin.getText().equals("Login")){
            FrmLogin frmLogin = new FrmLogin(this, true);
            frmLogin.setLocationRelativeTo(this);        
            frmLogin.setVisible(true);
        } else {
            user = null;            
            mnLogin.setText("Login");
            setMenuItemsEnabled(false);
            closeAllForm();
        }
    }//GEN-LAST:event_mnLoginActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        String databaseName = "ekspedisi";
        String password = ""; // Bisa ditanyakan ke user, atau dari input yang lebih aman
        String user_db = "root";

        String dateFormat = "yyyy-MM-dd_HH-mm-ss";
        SimpleDateFormat sdf = new SimpleDateFormat(dateFormat);
        String timestamp = sdf.format(new Date());

        // Folder backup (di folder yang sama dengan file JAR)
        String backupFolder = System.getProperty("user.dir") + File.separator + "backup";
        File dir = new File(backupFolder);
        if (!dir.exists()) {
            dir.mkdirs();  // Membuat folder backup jika belum ada
        }

        // Menentukan nama file backup
        String fileName = "bak_" + databaseName + "_" + timestamp + ".sql";
        String backupFilePath = backupFolder + File.separator + fileName;

        // Menentukan command untuk menjalankan mysqldump
        String command = String.format(
            "mysqldump -u %s %s -r %s", 
            user_db, databaseName, backupFilePath
        );

        // Tentukan perintah sesuai dengan platform
        String os = System.getProperty("os.name").toLowerCase();
        ProcessBuilder processBuilder;

        if (os.contains("win")) {
            // Windows
            processBuilder = new ProcessBuilder("cmd", "/c", command);
        } else {
            // Linux/MacOS
            processBuilder = new ProcessBuilder("bash", "-c", command);
        }

        // Eksekusi command menggunakan ProcessBuilder
        try {
            // Menjalankan perintah
            Process process = processBuilder.start();

            // Menangani output error dari proses
            InputStream errorStream = process.getErrorStream();
            InputStreamReader errorReader = new InputStreamReader(errorStream);
            BufferedReader bufferedErrorReader = new BufferedReader(errorReader);

            String line;
            StringBuilder errorOutput = new StringBuilder();
            while ((line = bufferedErrorReader.readLine()) != null) {
                errorOutput.append(line).append("\n");
            }

            int exitCode = process.waitFor();

            // Jika backup berhasil, exitCode = 0
            if (exitCode == 0) {
                AppUtils.showInfoDialog("Backup berhasil disimpan di: " + backupFilePath);
            } else {
                // Menampilkan error dari output
                AppUtils.showErrorDialog("Terjadi kesalahan saat melakukan backup.\n" + errorOutput.toString());
            }
        } catch (IOException | InterruptedException e) {
            AppUtils.showErrorDialog("Terjadi kesalahan saat melakukan backup. \n" + e.getMessage());
        }
    
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmDaftarJurnal frmDaftarJurnal = new FrmDaftarJurnal();
        desktopPane.add(frmDaftarJurnal);
        frmDaftarJurnal.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        FrmJenisTransaksi frmJenisTransaksi = new FrmJenisTransaksi(user);
        desktopPane.add(frmJenisTransaksi);
        frmJenisTransaksi.setVisible(true);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    
    public void setMenuItemsEnabled(boolean enabled) {
        for (int i = 0; i < jMenuBar1.getMenuCount(); i++) {
            JMenu menu = jMenuBar1.getMenu(i);
            if (menu != null) {
                for (int j = 0; j < menu.getItemCount(); j++) {
                    JMenuItem menuItem = menu.getItem(j);
                    if (menuItem != null) {
                        String itemText = menuItem.getText();

                        // Hanya disable/enable menu selain "Login" dan "Exit"
                        if (!itemText.equalsIgnoreCase("Login") && !itemText.equalsIgnoreCase("Exit")) {
                            menuItem.setEnabled(enabled);
                        }
                    }
                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem miArmada;
    private javax.swing.JMenuItem miCustomer;
    private javax.swing.JMenuItem miTransaksiKas;
    private javax.swing.JMenuItem mnLogin;
    // End of variables declaration//GEN-END:variables

    private void closeAllForm() {
        for (JInternalFrame frame : desktopPane.getAllFrames()) {
            try {
                frame.setClosed(true); // Menutup frame
            } catch (PropertyVetoException ex) {
                AppUtils.showErrorDialog("Gagal tutup semua form dengan error \n" + ex.getMessage());
            }
        }
    }
    
    public void SetCaptionMenuLogin(String Caption){
        mnLogin.setText(Caption);
    }
}
